# @package _group_

name: carla_${dataset.resolution}
camera:
  fov: 30.0
  ray_start: 0.75
  ray_end: 1.25
  dist: spherical_uniform
  radius: 1.0
  horizontal_stddev: 3.141592653589793
  vertical_stddev: 0.7417649320975901
  horizontal_mean: 0.0
  vertical_mean: 0.7417649320975901
cube_scale: 0.475
white_back: true
last_back: false
