# @package _group_

name: shapenet_${dataset.resolution}
camera:
  fov: 25.0
  ray_start: 0.75
  ray_end: 1.25
  dist: spherical_uniform
  radius: 0.8
  horizontal_stddev: 3.141592653589793
  vertical_stddev: 0.05
  horizontal_mean: 0.0
  vertical_mean: 1.0842557266318587
cube_scale: 0.55
white_back: true
last_back: false
c_dim: 513
