# @package _group_

# Checkpoint loading options
ckpt:
  network_pkl: ~ # Network pickle filename
  networks_dir: ~ # Network pickles directory
  selection_metric: fid2k_full # Which metric to use when selecting the best ckpt?
  reload_code: false # If we changed the code and what to run with the new code, we can reload it.

# Randomness options
num_seeds: ~ # The number of samples to generate
seeds: ~ # You can optionally override the `seed` argument by specifying seeds manually.


# Main options
cube_size: 0.3
volume_res: 256
max_batch_res: 32
voxel_origin: [0.0, 0.0, 0.0]
output_dir: shapes
thresh_percentile: 97.5
save_obj: false
save_mrc: true

# Miscelaneous options
verbose: false
truncation_psi: 0.7
